name: CI

on:
  push:
    tags:
      - '*'
  schedule:
      - cron: "0 4 * * *"

env:
  VCPKG_COMMIT_ID: "14e7bb4ae24616ec54ff6b2f6ef4e8659434ea44"
  CMAKE_BUILD_PRESET: "windows-release"
  MMX_VERSION: ${{ github.ref_name }}
  MMX_WIN_PACK: "TRUE"

jobs:
  msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          
      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ env.CMAKE_BUILD_PRESET }}
          buildPreset: ${{ env.CMAKE_BUILD_PRESET }}
   
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "build"
          path: ./build/${{ env.CMAKE_BUILD_PRESET }}/!bin/Release/*.*

      - name: Run CPack
        run: cpack -C Release --config build/${{ env.CMAKE_BUILD_PRESET }}/CPackConfig.cmake -B build/${{ env.CMAKE_BUILD_PRESET }}/!package

      - name: Zip files
        run: Get-ChildItem "./build/${{ env.CMAKE_BUILD_PRESET }}/!package" -Filter *.exe | Foreach-Object { 7z a ( (Convert-Path $_.PSParentPath) + "\"  + $_.BaseName + ".zip") $_.FullName }

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "package"
          path: ./build/${{ env.CMAKE_BUILD_PRESET }}/!package/*.exe

      - name: Upload a Build Artifact to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/${{ env.CMAKE_BUILD_PRESET }}/!package/*.zip
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
